import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home({ data }) {
  const { posts } = data.response;
  // console.log(posts[0].photos[0].original_size.url);
  // const [posts, setPosts] = useState(posts)

  return (
    <div className={styles.container}>
      <Head>
        <title>Living Digital Archives</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {posts?.map((post) => {
        return (
          <div key={post.id}>
            <div dangerouslySetInnerHTML={{ __html: post.caption }} />
            <img src={post.photos[0].original_size.url} />
          </div>
        );
      })}
    </div>
  );
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(
    `https://api.tumblr.com/v2/blog/oneterabyteofkilobyteage.tumblr.com/posts/photo?api_key=${process.env.API_KEY}&limit=50`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
